<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-009" ignored="9" name="Default test" tests="2" failures="1" timestamp="2022-04-29T18:36:38 IST" time="69.341" errors="0">
  <testcase name="LoginSuccessfull1_POC" time="33.043" classname="com.cma.testcases.TC_LocalTest"/>
  <testcase name="LoginSuccessfull2_POC" time="31.403" classname="com.cma.testcases.TC_LocalTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.cma.testcases.TC_LocalTest.LoginSuccessfull2_POC(TC_LocalTest.java:67)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- LoginSuccessfull2_POC -->
  <testcase name="Registration_POC" time="0.0" classname="com.cma.testcases.TC_LocalTest">
    <ignored/>
  </testcase> <!-- Registration_POC -->
  <testcase name="VerifyDisAgrrement" time="0.0" classname="com.cma.testcases.TC_LocalTest">
    <ignored/>
  </testcase> <!-- VerifyDisAgrrement -->
  <testcase name="LoginFailed_POC" time="0.0" classname="com.cma.testcases.TC_LocalTest">
    <ignored/>
  </testcase> <!-- LoginFailed_POC -->
  <testcase name="VerifySearchProject" time="0.0" classname="com.cma.testcases.TC_LocalTest">
    <ignored/>
  </testcase> <!-- VerifySearchProject -->
  <testcase name="VerifyUploadFileFunctionality" time="0.0" classname="com.cma.testcases.TC_LocalTest">
    <ignored/>
  </testcase> <!-- VerifyUploadFileFunctionality -->
  <testcase name="VerifyAgrrement" time="0.0" classname="com.cma.testcases.TC_LocalTest">
    <ignored/>
  </testcase> <!-- VerifyAgrrement -->
  <testcase name="LoginSuccessfull_POC" time="0.0" classname="com.cma.testcases.TC_LocalTest">
    <ignored/>
  </testcase> <!-- LoginSuccessfull_POC -->
  <testcase name="VerifySaveButtonFunctionality" time="0.0" classname="com.cma.testcases.TC_LocalTest">
    <ignored/>
  </testcase> <!-- VerifySaveButtonFunctionality -->
  <testcase name="VerifyGetTaskFunctionality" time="0.0" classname="com.cma.testcases.TC_LocalTest">
    <ignored/>
  </testcase> <!-- VerifyGetTaskFunctionality -->
</testsuite> <!-- Default test -->
